[global.limits]
file="15 GiB"
data-form="15 GiB"
form="15 GiB"
[default.databases.sea_orm]
url="sqlite://db.sqlite?mode=rwc"


[default]
temp_dir = "temp/temp"
[debug]
temp_dir = "temp/temp"
[release]
address = "0.0.0.0"
port = 8000
temp_dir = "temp/temp"