//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::chunks::Entity as Chunks;
pub use super::files::Entity as Files;
pub use super::task_list::Entity as TaskList;
pub use super::users::Entity as Users;
